# block some countries
[[redirects]]
    from = "/*"
    to = "/public/deny.html"
    status = 451
    force = true
    conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","SD","SY","ZW"]}

# Redirect the routes to the index.html
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
